name: CI/CD

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'

jobs:
  ci_cd:
    runs-on: 'windows-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Heleonix.Build
        run: nuget install Heleonix.Build -version ${{ vars.Hx_Ver }} -outputdirectory ../hxb
      - name: Validate
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_NetValidate
      - name: ChangeLog
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_ChangeLog_GitHubCommit
        env:
          Hx_ChangeLog_GitHubCommit_Token: ${{ secrets.GH_PAT }}
      - name: Build
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_NetBuild
      - name: Test
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_OpenCover
        env:
          Hx_OpenCover_FilePathReplacement: ${{ vars.Hx_OpenCover_FilePathReplacement }}
          Hx_OpenCover_FilePathRegExp: ${{ vars.Hx_OpenCover_FilePathRegExp }}
      - name: Publish
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_NugetPublish
        env:
          Hx_NugetPublish_SourceURL: ${{ vars.Hx_NugetPublish_SourceURL }}
          Hx_NugetPublish_APIKey: ${{ secrets.NUGET_API_KEY }}
      - name: Release
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_Release_GitHub
        env:
          Hx_Release_GitHub_Token: ${{ secrets.GH_PAT }}
      - name: Docs
        run: dotnet msbuild ../hxb/Heleonix.Build.${{ vars.Hx_Ver }}/Main.hxbproj -p:Hx_In_Targets=Hx_DocFX_Git
        env:
          Hx_DocFX_Git_BranchName: ${{ vars.Hx_DocFX_Git_BranchName }}
          Hx_DocFX_Git_User: ${{ vars.Hx_DocFX_Git_User }}
          Hx_DocFX_RepositoryUrl: ${{ vars.Hx_DocFX_RepositoryUrl }}
          Hx_DocFX_Git_Token: ${{ secrets.GH_PAT }}
